#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt"
cookbook "git"
cookbook "sqlite"
cookbook 'postgresql'
cookbook "redis"
cookbook "nodejs"
cookbook "memcached"
cookbook "imagemagick"
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'ruby_build'
